// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1uU2pMCQL7lTqJEyKPj-4zE8GTXzD7ew',
    appId: '1:885144684281:android:9847059f52a0d1da008428',
    messagingSenderId: '885144684281',
    projectId: 'ecli-14d4c',
    storageBucket: 'ecli-14d4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiR_z4OVdUeMsgN67MMxpR-ggM_INuK4c',
    appId: '1:885144684281:ios:9beaddd6b1c742c2008428',
    messagingSenderId: '885144684281',
    projectId: 'ecli-14d4c',
    storageBucket: 'ecli-14d4c.appspot.com',
    androidClientId: '885144684281-ms6ol0suc2s6sku8o5a3ejur2rm7pg73.apps.googleusercontent.com',
    iosClientId: '885144684281-foh2ctb2o3kuhc7outhnfj8lhnlv104v.apps.googleusercontent.com',
    iosBundleId: 'br.com.esigp',
  );

}